site_name: MovFX
site_url: https://mediatoolbox-org.github.io/movfx
repo_url: https://github.com/mediatoolbox-org/movfx
docs_dir: ./docs
site_dir: ./build

nav:
  - index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  # from gen-files
  - API: api/

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  logo: ./images/logo.png
  favicon: ./images/favicon.png
  palette:
    scheme: slate
    primary: white
    accent: lime

plugins:
  - search
  - macros
  - autorefs
  - gen-files:
      scripts:
        - scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [src]

          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            docstring_style: numpy
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_root_full_path: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
  - mkdocs-jupyter:
      execute: false
      ignore:
        - "*.py"
      include_source: true
      theme: dark

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/static/icons
  - pymdownx.details
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      style_plain_text: python
  - pymdownx.magiclink:
      provider: github
      repo_url_shortener: true
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra:
  project_name: "MovFX"
  team:
    - name: "Active maintainers"
      members:
        - xmnlab
    - name: "Former maintainers"
      members:
        - xmnlab
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xmnlab
    - icon: fontawesome/brands/github
      link: https://github.com/mediatoolbox-org/movfx
  support_levels:
    supported:
      icon: :material-check-decagram:{ .verified }
      description: Tested in CI. If this doesn't work for you, please [file an issue](https://github.com/mediatoolbox-org/movfx/issues/new).
    bug:
      icon: :material-bug:{ .bug }
      description: Should work but doesn't because upstream is broken. Supported on a best-effort basis.
    unsupported:
      icon: :material-cancel:{ .cancel }
      description: Unlikely to ever be supported or no upstream support.

copyright: "Copyright &copy; 2026, MediaToolBox Team"
